/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import AppPackage.AnimationClass;
import Modelo.Empleado;
import Control.CEmpleado;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jdgom
 */
public class JFLogin extends javax.swing.JFrame {
    FondoPane2 fondo = new FondoPane2();
    /**
     * Creates new form JFLogin
     */
    public JFLogin() {
        this.setContentPane(fondo);
        initComponents();
        
        this.setLocationRelativeTo(null);
        jScrollPane1.setVisible(false);
        
    }
    
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Files/icon2.png"));
        return retValue;
    }
    
    
    public boolean ValidarEmail(String email) {
        // Patron para validar el email
        Pattern pattern = Pattern.compile("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$");
        Matcher mather = pattern.matcher(email);
        return mather.find();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new FondoPane2();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsuarioL = new javax.swing.JTextField();
        txtPasswordL = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaListado = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        ingrasr = new javax.swing.JButton();
        che = new javax.swing.JLabel();
        nota = new javax.swing.JLabel();
        jPanel3 = new FondoPane2();
        btnSalir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/padlock.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 30, 30));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/user (1).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 30, 30));

        txtUsuarioL.setBackground(new java.awt.Color(211, 112, 112));
        txtUsuarioL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtUsuarioL.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuarioL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtUsuarioL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioLActionPerformed(evt);
            }
        });
        txtUsuarioL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsuarioLKeyReleased(evt);
            }
        });
        jPanel1.add(txtUsuarioL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 268, 30));

        txtPasswordL.setBackground(new java.awt.Color(211, 112, 112));
        txtPasswordL.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txtPasswordL.setForeground(new java.awt.Color(255, 255, 255));
        txtPasswordL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        txtPasswordL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordLActionPerformed(evt);
            }
        });
        jPanel1.add(txtPasswordL, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 270, 30));

        tablaListado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaListado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 16, 10));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/grupo.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 130, 120));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/menu.png"))); // NOI18N
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 30));

        l3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/logotipo-de-google-drive.png"))); // NOI18N
        jPanel1.add(l3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 90, 30, 20));

        l1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/internet (1).png"))); // NOI18N
        jPanel1.add(l1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 50, 30, 20));

        l2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/gmail.png"))); // NOI18N
        jPanel1.add(l2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 70, 30, 20));

        ingrasr.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ingrasr.setForeground(new java.awt.Color(255, 255, 255));
        ingrasr.setText("Ingresar");
        ingrasr.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ingrasr.setBorderPainted(false);
        ingrasr.setContentAreaFilled(false);
        ingrasr.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ingrasr.setDefaultCapable(false);
        ingrasr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ingrasrMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ingrasrMouseExited(evt);
            }
        });
        ingrasr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingrasrActionPerformed(evt);
            }
        });
        jPanel1.add(ingrasr, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 115, 34));

        che.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        che.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(che, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 200, 30, 30));

        nota.setFont(new java.awt.Font("Arial", 2, 11)); // NOI18N
        nota.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(nota, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 240, 20));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salida.png"))); // NOI18N
        btnSalir.setBorder(null);
        btnSalir.setBorderPainted(false);
        btnSalir.setContentAreaFilled(false);
        btnSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salida.png"))); // NOI18N
        btnSalir.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salida.png"))); // NOI18N
        btnSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/salida.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/flecha-hacia-abajo-para-navegar (1).png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/flecha-hacia-abajo-para-navegar (1).png"))); // NOI18N
        jButton1.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/flecha-hacia-abajo-para-navegar (1).png"))); // NOI18N
        jButton1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/flecha-hacia-abajo-para-navegar (1).png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Red Technology Logo (1) (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 72, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(69, 69, 69))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        AnimationClass internet=new AnimationClass();
        internet.jLabelXRight(-30, 0, 10, 5, l1);
        AnimationClass gmail=new AnimationClass();
        gmail.jLabelXRight(-30, 0, 10, 5, l2);
        AnimationClass drive=new AnimationClass();
        drive.jLabelXRight(-30, 0, 10, 5, l3);
        
        
        AnimationClass internett=new AnimationClass();
        internett.jLabelXLeft(0, -30, 10, 5, l1);
        AnimationClass gmaill=new AnimationClass();
        gmaill.jLabelXLeft(0, -30, 10, 5, l2);
        AnimationClass drivee=new AnimationClass();
        drivee.jLabelXLeft(0, -30, 10, 5, l3);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setState(JFLogin.ICONIFIED);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ingrasrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingrasrActionPerformed
       
        try {
            DefaultTableModel modelo;
            CEmpleado func = new CEmpleado();
            Empleado dts = new Empleado();
            
            

            dts.setLogin(txtUsuarioL.getText());
            dts.setPassword(txtPasswordL.getText());

            modelo = func.login(dts.getLogin(), dts.getPassword());

            tablaListado.setModel(modelo);
            if (func.totalregistros > 0) {
                this.dispose();
                JFMenu form = new JFMenu();
                form.toFront();
                form.setVisible(true);
                JFMenu.lblidpersona.setText(tablaListado.getValueAt(0, 0).toString());
                JFMenu.lblNombre.setText(tablaListado.getValueAt(0, 1).toString());
                JFMenu.lblAPaterno.setText(tablaListado.getValueAt(0, 2).toString());
                JFMenu.lblAMaterno.setText(tablaListado.getValueAt(0, 3).toString());
                JFMenu.lblAcceso.setText(tablaListado.getValueAt(0, 4).toString());
                JFMenu.lblPresentacion.setText(JFMenu.lblNombre.getText() + " " + JFMenu.lblAPaterno.getText() + " " + JFMenu.lblAMaterno.getText());
                Icon perfil;
                perfil = new ImageIcon(getClass().getResource("/Files/emblem.png"));
                JFMenu.lblFoto.setIcon(perfil);
                if (!JFMenu.lblAcceso.getText().equals("Administrador")) {
                    JFMenu.mnuArchivo.setEnabled(false);
                    JFMenu.mnuConfiguraciones.setEnabled(false);
                    perfil = new ImageIcon(getClass().getResource("/Files/fotoR.png"));
                    JFMenu.lblFoto.setIcon(perfil);
                }

            } else {
                JOptionPane.showMessageDialog(rootPane, "Acceso Denegado", "Acceso al Sistema", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_ingrasrActionPerformed

    private void ingrasrMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrasrMouseEntered
        ingrasr.setForeground(Color.getHSBColor(204, 0, 0));
    }//GEN-LAST:event_ingrasrMouseEntered

    private void ingrasrMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ingrasrMouseExited
        ingrasr.setForeground(Color.WHITE);
    }//GEN-LAST:event_ingrasrMouseExited

    private void txtUsuarioLKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsuarioLKeyReleased
       Boolean vl=ValidarEmail(txtUsuarioL.getText());
       if(!vl==false){
           che.setText("");
           ingrasr.setEnabled(true);
           txtPasswordL.setEnabled(true);
           nota.setText("");
       }else if(txtUsuarioL.getText().length() == 0){
           che.setText("");
           ingrasr.setEnabled(false);
           txtPasswordL.setEnabled(false);
           nota.setText("");
       }else{
           che.setText("*");
           ingrasr.setEnabled(false);
           txtPasswordL.setEnabled(false);
           nota.setText("Los Campos Con (*) son declarados No Válido");
       }
    }//GEN-LAST:event_txtUsuarioLKeyReleased

    private void txtUsuarioLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioLActionPerformed
       txtUsuarioL.transferFocus();
    }//GEN-LAST:event_txtUsuarioLActionPerformed

    private void txtPasswordLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordLActionPerformed
        txtPasswordL.transferFocus();
    }//GEN-LAST:event_txtPasswordLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel che;
    private javax.swing.JButton ingrasr;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel nota;
    private javax.swing.JTable tablaListado;
    private javax.swing.JPasswordField txtPasswordL;
    private javax.swing.JTextField txtUsuarioL;
    // End of variables declaration//GEN-END:variables

    class FondoPane2 extends JPanel {

        private Image imagen;

        @Override
        public void paint(Graphics g) {
            imagen = new ImageIcon(getClass().getResource("/Files/fondologin.png")).getImage();

            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            setOpaque(false);

            super.paint(g);
        }
    }
    

}
